spring.application.name=TaskManagement
spring.datasource.url=jdbc:mysql://localhost:3306/tasksystem
spring.datasource.username=root
spring.datasource.password=----password---
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
poster=upload/
#spring.security.user.name=spj
#spring.security.user.password=spj
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=----email------
spring.mail.password=----mail 2FA password----
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
baseUrl = http://localhost:8080
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
jwt.secret=-----jwt secret code------